import type { Express } from "express";
import { requireAuthentication } from "../shared/auth/authentication-middleware.js";
import { authRoutes } from "./auth/auth.routes.js";
import { brandsRoutes } from "./brands/brands.routes.js";
import { cashRegisterRoutes } from "./cash-register/cash-register.routes.js";
import { clientsRoutes } from "./clients/clients.routes.js";
import { fiscalDocumentsRoutes } from "./fiscal-documents/fiscal-documents.routes.js";
import { healthRoutes } from "./health/health.routes.js";
import { paymentMethodsRoutes } from "./payment-methods/payment-methods.routes.js";
import { pickupReservationsRoutes } from "./pickup-reservations/pickup-reservations.routes.js";
import { productGroupsRoutes } from "./product-groups/product-groups.routes.js";
import { productsRoutes } from "./products/products.routes.js";
import { quotesRoutes } from "./quotes/quotes.routes.js";
import { reportsRoutes } from "./reports/reports.routes.js";
import { rootRoutes } from "./root/root.routes.js";
import { salesRoutes } from "./sales/sales.routes.js";
import { shippingOrdersRoutes } from "./shipping-orders/shipping-orders.routes.js";
import { stockAdjustmentsRoutes } from "./stock-adjustments/stock-adjustments.routes.js";
import { stockEntriesRoutes } from "./stock-entries/stock-entries.routes.js";
import { stockMovementsRoutes } from "./stock-movements/stock-movements.routes.js";
import { suppliersRoutes } from "./suppliers/suppliers.routes.js";
import { usersRoutes } from "./users/users.routes.js";

export function registerRoutes(app: Express): void {
  app.use(rootRoutes);
  app.use(healthRoutes);
  app.use(authRoutes);
  app.use(requireAuthentication);
  app.use(brandsRoutes);
  app.use(cashRegisterRoutes);
  app.use(clientsRoutes);
  app.use(fiscalDocumentsRoutes);
  app.use(paymentMethodsRoutes);
  app.use(pickupReservationsRoutes);
  app.use(productGroupsRoutes);
  app.use(productsRoutes);
  app.use(quotesRoutes);
  app.use(reportsRoutes);
  app.use(salesRoutes);
  app.use(shippingOrdersRoutes);
  app.use(stockAdjustmentsRoutes);
  app.use(stockEntriesRoutes);
  app.use(stockMovementsRoutes);
  app.use(suppliersRoutes);
  app.use(usersRoutes);
}
