export function showApiInfo() {
  return {
    code: 200,
    status: "success",
    data: {
      service: "loja-filtros-backend",
      version: "0.1.0",
      endpoints: [
        "/health",
        "/health/database",
        "/auth/setup",
        "/auth/login",
        "/auth/session",
        "/auth/logout",
        "/users",
        "/cash-register/current",
        "/cash-register/open",
        "/cash-register/close",
        "/sales",
        "/sales/:id/receipt",
        "/shipping-orders",
        "/pickup-reservations",
        "/quotes",
        "/quotes/:id/pdf",
        "/quotes/:id/shipping-order",
        "/purchase-invoices",
        "/purchase-invoices/import-xml",
        "/purchase-invoices/parse-xml",
        "/reports/overview",
        "/products",
        "/products/low-stock",
        "/payment-methods",
        "/clients",
        "/clients/cnpj/:cnpj",
        "/stock-adjustments",
        "/stock-entries",
        "/stock-movements",
        "/brands",
        "/product-groups",
        "/suppliers",
      ],
    },
  };
}
